lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  pipeline_name_conventions: False
  actions_awsfulltest: False
  nextflow_config:
    - custom_config
    - manifest.name
    - manifest.homePage

repository_type: pipeline
