repository_type: pipeline
nf_core_version: "3.0.2"
bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - assets/multiqc_config.yml
    - assets/nf-core-viralassembly_logo_light.png
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - docs/images/nf-core-viralassembly_logo_light.png
    - docs/images/nf-core-viralassembly_logo_dark.png
    - lib/NfcoreTemplate.groovy
    - lib/Utils.groovy
    - lib/WorkflowMain.groovy
    - lib/nfcore_external_java_deps.jar
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting_comment.yml
    - docs/README.md
    - LICENSE
    - .gitignore
  multiqc_config: False
  pipeline_name_conventions: False
  actions_awsfulltest: False
  nextflow_config: False

template:
  prefix: phac-nml
