lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  nextflow_config:
  - manifest.name
repository_type: pipeline

